config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :companies
  root 'home#index'
  get "/admin", to: "admin#index"
  namespace :admin do
    resources :jobs
    resources :companies
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/index.html.erb
<h1>Admin Page</h1>

<%= link_to "Back to Home", root_path %>

<p id="notice"><%= notice %></p>

<h1>管理公司資訊</h1>
<div style="float: right; margin-right: 20px;">
    <%= link_to 'New Company', new_admin_company_path %>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>公司名稱</th>
      <th>公司介紹</th>
      <th>公司理念</th>
      <th>媒體報導</th>
      <th>薪資福利</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.intro %></td>
        <td><%= company.idea %></td>
        <td><%= company.press %></td>
        <td><%= company.walfare %></td>
        <td><%= link_to 'Edit', edit_admin_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>目前職缺</h1>
<div style="float: right; margin-right: 20px;">
    <%= link_to 'New Job', new_admin_job_path %>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>職缺名稱</th>
      <th>工作內容</th>
      <th>條件要求</th>
      <th>公司福利</th>
      <th>薪資範圍</th>
      <th>開放</th>
      <th>所屬公司</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.name %></td>
        <td><%= job.detail %></td>
        <td><%= job.requirement %></td>
        <td><%= job.walfare %></td>
        <td><%= job.pay %></td>
        <td><%= job.open %></td>
        <td><%= job.company.name %></td>
        <td><%= link_to 'Edit', edit_admin_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>