config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :companies
  root 'home#index'
  get "/admin", to: "admin#index"
  namespace :admin do
    resources :jobs
    resources :companies
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::BaseController
  before_action :set_job, only: %i[ show edit update destroy ]

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @companies = Company.all
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
    @companies = Company.all
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to @admin
    else
      render :new
    
    #respond_to do |format|
    #  if @job.save
    #    redirect_to admin_path
    #    ormat.html { redirect_to @job, notice: "Job was successfully created." }
    #    format.json { render :show, status: :created, location: @job }
    #  else
    #    format.html { render :new, status: :unprocessable_entity }
    #    format.json { render json: @job.errors, status: :unprocessable_entity }
    #  end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:name, :detail, :requirement, :walfare, :pay, :open, :company_id)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.where(:open => true).all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @companies = Company.all
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
    @companies = Company.all
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)
    respond_to do |format|
      if @job.save
        format.html { redirect_to admin_url, notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to admin_url, notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to admin_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:name, :detail, :requirement, :walfare, :pay, :open, :company_id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/admin/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field" style="margin-top: 30px;">
  <h4><%= form.label "職缺名稱" %></h4>
    <%= form.text_field :name, class: "form-control", placeholder: "Full Stack Engineer" %>
  </div>

  <div class="field" style="margin-top: 30px;">
  <h4><%= form.label "工作內容" %></h4>
    <%= form.text_area :detail, class: "form-control", placeholder: "Work Days, Details ..." %>
  </div>

  <div class="field" style="margin-top: 30px;">
  <h4><%= form.label "條件要求" %></h4>
    <%= form.text_area :requirement, class: "form-control", placeholder: "Skill, Characteristic ..." %>
  </div>

  <div class="field" style="margin-top: 30px;">
  <h4><%= form.label "公司福利" %></h4>
    <%= form.text_area :walfare, class: "form-control", placeholder: "Drinks, Cookies ..." %>
  </div>

  <div class="field" style="margin-top: 30px;">
  <h4><%= form.label "薪資範圍" %></h4>
    <%= form.text_field :pay, class: "form-control", placeholder: "70,000 NTD/M"  %>
  </div>

  <div class="field" style="margin-top: 30px;">
  <h4><%= form.label "是否開放" %></h4>
    <%= form.check_box :open, class: "form-check-input" %>
  </div>

  <div class="field" style="margin-top: 30px;">
    <h4><%= form.label "所屬公司" %></h4>
    <%= form.select :company_id, options_for_select(@companies.collect{ |company| [company.name, company.id] }, job.company_id), {}, {:class => 'form-control'} %>
  </div>
  
  <div class="actions d-flex justify-content-center" style="margin-top: 100px; margin-bottom: 100px;">
    <%= form.submit class: 'btn btn-outline-dark'%>
  </div>
<% end %>

app/views/admin/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

app/views/admin/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>
<!--
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Detail</th>
      <th>Requirement</th>
      <th>Walfare</th>
      <th>Pay</th>
      <th>Open</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.name %></td>
        <td><%= job.detail %></td>
        <td><%= job.requirement %></td>
        <td><%= job.walfare %></td>
        <td><%= job.pay %></td>
        <td><%= job.open %></td>
        <td><%= job.company.name %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->
<div class="list-group" style="margin-top: 30px;">
  <% @jobs.each do |job| %>
  <%= link_to job.name, job, class: "list-group-item list-group-item-action" %>
  <% end %>
</div>
<br>

<%= link_to "Back to Home", root_path %>
<!--
<%= link_to 'New Job', new_job_path %>
-->

app/views/admin/jobs/new.html.erb
<h1>新增職缺</h1>

<%= render 'form', job: @job %>

app/views/admin/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><strong><%= @job.name %></strong></h1>
</p>

<div style="margin-left: 30px;">
  <p>
    <h3><strong>工作內容</strong></h3>
    <h5 style="color: gray;"><%= @job.detail %></h5>
  </p>

  <p>
    <h3><strong>條件要求</strong></h3>
    <h5 style="color: gray;"><%= @job.requirement %></h5>
  </p>

  <p>
    <h3><strong>公司福利</strong></h3>
    <h5 style="color: gray;"><%= @job.walfare %></h5>
  </p>

  <p>
    <h3><strong>薪資範圍</strong></h3>
    <h5 style="color: gray;"><%= @job.pay %></h5>
  </p>

  <!--<p>
    <strong>Open:</strong>
    <%= @job.open %>
  </p>-->

  <p>
    <h3><strong>公司</strong></h3>
    <h5 style="color: gray;"><%= @job.company.name %></h5>
  </p>
</div>

<!-- <%= link_to 'Edit', edit_job_path(@job) %> 
<%= link_to 'Back', jobs_path %> -->
<br>
<div class="d-flex justify-content-center" style="margin-top: 150px;">
  <button type="button" class="btn btn-primary btn-lg btn-block" style="padding: 10px 30px; border-radius: 7px;">現在應徵</button>
</div>